[package]
name = "chess-gui"
version = "0.1.0"
authors = ["arian"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustchessian = { git = "https://github.com/INDAPlus20/oskhen-chess.git"}
ggez= "0.5"
